ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
AVRDUDE_CONF = /etc/avrdude.conf
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/hardware/arduino/libraries
BOARDS_TXT = /usr/share/arduino/hardware/arduino/boards.txt
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders

BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyS6
ARDUINO_LIBS =

include Makefile.linux
